### ISSUE TITLE
JJRC H8D? What protocol does it use?

### ISSUE THREAD

**Issue by brezuicabogdan** [goebish/nrf24_multipro#11]
Hi,

I know this is not an issue but I was wondering if you happen to know what protocol does JJRC H8D qud uses? I saw that H8C uses V2x2 but didn t find any confirmation on H8D. I Tried your library with V2x2 proto and doesn`t work. After playing around with the order of the channels in the packet I got SOME things to work but can t get it to fully fly.

Any info is greatly appreciated. 

Thank you.

**Comment by goebish** [comment]
I don't have a H8D myself, but if you got it to bind it shouldn't be far from working.
Please come to the forum, perhaps we'll be able to help.
http://www.rcgroups.com/forums/showthread.php?t=2367400&page=48
