### ISSUE TITLE
syma x5hw

### ISSUE THREAD

**Issue by silver13** [goebish/nrf24_multipro#20]
I have a syma x5hw that I can't bind to, do you know if it uses a different protocol or is it my board?

I have tried both options

**Comment by goebish** [comment]
It's probably a new protocol if it doesn't bind with one of the 2 SymaX protocols.
Please post a capture of the stock TX to the Deviation forums when you have a chance :)

**Comment by silver13** [comment]
thanks, I have only the board, and it might be damaged, so don't draw any conclusions from this.
