### ISSUE TITLE
Eachine E010 using different protocols?

### ISSUE THREAD

**Issue by mgrapiniak** [goebish/nrf24_multipro#26]
Hi,

Has Eachine released different protocols for their E010 product?
I do have a cheap Banggood product which I have reflashed using current version of your firmware (I know it is unsupported completely and understand why) but before purchasing your solution I'd like to know if that is the case.
Suprisingly Binding to cx-10 works as expected but no go with E010. Has anyone cone across this issue with your module?

**Comment by goebish** [comment]
There's only 1 E010 protocol, but this protocol requires an accurate oscillator circuitry, which the BG module does not have. My modules are guarantied to work ;)

**Comment by mgrapiniak** [comment]
Thanks for the info. 
Well this is what you get if you buy cheap stuff right?;)
Feel free to close out the ticket.

Cheers!
