### ISSUE TITLE
FrSky

### ISSUE THREAD

**Issue by whyvas** [goebish/nrf24_multipro#27]
Hey, so I bought a QX90C with FrSky mode along with the module that banggood is selling that is apparently ripping off your code. I thought it would allow my 9XR to output the FrSky protocol but it seems it doesn't. It's compatible with FrSky radios... sigh.

My question to you is, can this be programmed to output FrSky?

**Comment by goebish** [comment]
Hi,

No it's not compatible, the nrf24l01 doesn't use the same modulation 
than the CC2500 (required for FrSky protocol).

/ Goebish
