### ISSUE TITLE
some optimization perhaps

### ISSUE THREAD

**Issue by silver13** [goebish/nrf24_multipro#31]
https://github.com/goebish/nrf24_multipro/blob/869a6b4e7206353a8152595f86dd8af2e66a8dfa/nRF24_multipro/XN297_emu.ino#L140

sorry to open an issue, don't seem to know how to leave a comment lol

I think the line is equivalent to 

        msg[i] = bit_reverse(msg[i]^xn297_scramble[i+xn297_addr_len]) ;

**Comment by goebish** [comment]
I think you're right, I'll change it once (if 😛 ) I implement crc in receive.

**Comment by silver13** [comment]
cool, haven't tested it
