### ISSUE TITLE
[Question] SoftSPI

### ISSUE THREAD

**Issue by npag** [goebish/nrf24_multipro#39]
Hi! Is software SPI supported on all pins? Or must a certain pin offer a certain feature for it to work? For example PWM for a MISO pin? I'd like to use all the analog pins for the connection of the nrf24 module but I cannot say for certain if I will run into any long term problems.

**Comment by goebish** [comment]
You can use any pin, but don't forget to modify the outputs (PCx for AIN pins).

**Comment by npag** [comment]
Okay thank you for the information, I will look into it.
