### ISSUE TITLE
Not clear enough

### ISSUE THREAD

**Issue by IgnacioEscorza** [goebish/nrf24_multipro#4]
Dear Goebish,
First of all, thank you for adding Bayang/Eachine protocol support. But to be honest, I'll be glad to make a tutorial of How-To use nrf24-multipro because it is not clear, at least for me, not even how to compile, connect, opentx, and more. Thanks
Plus, when I try to compile on arduino IDE 1.6.6, produces this error:

Arduino:1.6.6 (Windows 8), Placa:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

C:\Users\Ignacio Escorza\Documents\_IPN Ago - Dic 15\PI\nrf24l01+\nrf24_multipro-master\nRF24_multipro\softSPI.ino:16:0: warning: "NOP" redefined [enabled by default]

 #define NOP() __asm__ __volatile__("nop")

 ^

In file included from C:\Users\Ignacio Escorza\Documents\_IPN Ago - Dic 15\PI\nrf24l01+\nrf24_multipro-master\nRF24_multipro\nRF24_multipro.ino:33:0:

sketch\iface_nrf24l01.h:112:0: note: this is the location of the previous definition

 #define NOP           0xFF 

 ^

**Comment by goebish** [comment]
oops, you should be able to compile now.
Come to http://www.rcgroups.com/forums/showthread.php?t=2367400 if you need help.
