### ISSUE TITLE
Bayang Channel 11 and 12 missing

### ISSUE THREAD

**Issue by SirDomsen** [goebish/nrf24_multipro#45]
Hi Goebish,

is it possible to add Channel 11 and 12 (CHANNEL_TO and CHANNEL_EMGSTOP in Packet[3])? I see it's in Deviation for quite a while now:

https://github.com/DeviationTX/deviation/blob/master/src/protocol/bayang_nrf24l01.c

Would be cool since I'm just building a new module for a Flymate who owns a Graupner MZ-24. 

Would enhance compatibility to Silverware and stock BWhoop

Cheers
Domsen

**Comment by SirDomsen** [comment]
Wow, that was fast!
Right, I didn't think about that. So I'd recommend to add CH_EMGSTOP since thats the emergency throttle cut for stock BWhoop.

**Comment by goebish** [comment]
Done, CH11 = Emergency stop

**Comment by SirDomsen** [comment]
Awesome, Thanks very much!
