### ISSUE TITLE
NRF24 Receiver?

### ISSUE THREAD

**Issue by fbiego** [goebish/nrf24_multipro#50]
Is it possible to decode and receive signals from the transmitter to Arduino using the nrf24l01 module so that I can control projects with one transmitter?

The transmitter I have is based on XNS1042CV
![txd-3s_tx](https://user-images.githubusercontent.com/45796740/60142180-5f9b3400-97c1-11e9-8cf3-b97dad7ed725.png)

**Comment by goebish** [comment]
No, this project has no XN297 / XNS1042 dumper.
DeviationTX and Multi Protocol Module has one
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module
